CI: Add a cross-build for ARMEL architecture

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,6 +2,18 @@ stages:
   - build
   - deploy
 
+variables:
+  CONF_BUILD: "x86_64-linux-gnu"
+  CONF_TARGET: "xtensa-esp32-elf"
+  ARCHIVE_TOOL: "tar czvf"
+  ARCHIVE_EXT: "tar.gz"
+
+  TARBALL_NAME: ct-ng-v1.22.0-tarballs-1.tar
+# Local tarball address is TARBALL_URL
+
+before_script:
+  - set -o errexit; set -o pipefail; set -o nounset
+
 # Prepare release name/number
 .get_release_name: &get_release_name |
   VER_DESC=$(git describe | sed -E -n 's|.*crosstool-ng-([0-9]+).([0-9]+).([0-9]+)-([0-9]+)-g([0-9a-f]{7}).*|\1.\2.\3-\4-g\5|gp')
@@ -15,8 +27,8 @@ stages:
 .build_ctng: &build_ctng |
   ./bootstrap
   ./configure --enable-local
-  make install
-  ./ct-ng xtensa-esp32-elf
+  make
+  ./ct-ng ${CONF_TARGET}
 
 # ct-ng options common for all platforms
 .configure_common: &configure_common |
@@ -25,23 +37,40 @@ stages:
   echo "CT_LOG_EXTRA=y" >> .config
   echo "CT_LOG_LEVEL_MAX=\"EXTRA\"" >> .config
 
+# Configuration specific to Docker
+.configure_docker: &configure_docker |
+  echo "CT_ALLOW_BUILD_AS_ROOT=y" >> .config
+  echo "CT_ALLOW_BUILD_AS_ROOT_SURE=y" >> .config
+
 # If PIE is enabled by default in build GCC, add a flag to disable it
 .configure_linux_no_pie: &configure_linux_no_pie |
   gcc -v |& grep -- --enable-default-pie > /dev/null && echo "CT_EXTRA_LDFLAGS_FOR_HOST=\"-no-pie\"" >> .config
 
-# Configuration specific to Docker
-.configure_docker: &configure_docker |
-  echo "CT_ALLOW_BUILD_AS_ROOT=y" >> .config
-  echo "CT_ALLOW_BUILD_AS_ROOT_SURE=y" >> .config  
+# Configuration specific to crossbuilds
+.configure_crossbuild: &configure_crossbuild |
+  echo "CT_CANADIAN=y" >> .config
+  echo "CT_BUILD=\"${CONF_BUILD}\"" >> .config
+  echo "CT_BUILD_PREFIX=\"${CONF_BUILD}-\"" >> .config
+  echo "CT_BUILD_SUFFIX=\"\"" >> .config
+  echo "CT_HOST=\"${CONF_HOST}\"" >> .config
+  echo "CT_HOST_PREFIX=\"${CONF_HOST}-\"" >> .config
+  echo "CT_HOST_SUFFIX=\"\"" >> .config
+
+  # No support Python in GDB in cross-compilation now,
+  # see https://stackoverflow.com/questions/33512541/cross-compiling-gdb-for-arm-with-python-failed#34625177
+  echo "# CT_GDB_CROSS_PYTHON is not set" >> .config
 
 # Download tarballs and extract them into build directory
 .get_tarballs: &get_tarballs |
-  wget https://ci.espressif.cn:42348/cache/ct-ng-tarballs.tar
-  test "$(shasum -a 256 ct-ng-tarballs.tar | cut -d ' ' -f 1)" = "9b3a5662474bbc53613b6d4d2ef00e7767e0e1c1f20dfed1193654739506a3ce"
+  echo Downloading tarballs...
+  wget --no-verbose ${TARBALL_URL}/${TARBALL_NAME}
+  wget --no-verbose ${TARBALL_URL}/${TARBALL_NAME}.sha256
+  echo Checking sum...
+  sha256sum -c ${TARBALL_NAME}.sha256 || exit 1
   mkdir -p .build/tarballs
-  cd .build/tarballs
-  tar xvf ../../ct-ng-tarballs.tar
-  cd ../../
+  pushd .build/tarballs
+  tar xvf ../../${TARBALL_NAME}
+  popd
 
 # Actual build
 .build_toolchain: &build_toolchain |
@@ -52,17 +81,18 @@ stages:
 .package_toolchain: &package_toolchain |
   mkdir -p dist
   cd builds
-  rm xtensa-esp32-elf/build.log.bz2
-  ${ARCHIVE_TOOL} ${REL_NAME}.${ARCHIVE_EXT} xtensa-esp32-elf/
+  rm ${CONF_TARGET}/build.log.bz2
+  ${ARCHIVE_TOOL} ${REL_NAME}.${ARCHIVE_EXT} ${CONF_TARGET}/
   ls -l
   mv ${REL_NAME}.${ARCHIVE_EXT} ../dist/
   cd ../
-
+  #TODO generate checksum
 
 # Common template for all builds
 .build_template: &build_template
   stage: build
-
+  tags:
+    - build
   artifacts:
     paths:
       - .config
@@ -84,33 +114,23 @@ stages:
     - *package_toolchain
 
 build_linux:
-  tags:
-    - build
+  <<: *build_template_linux
   image: $CI_DOCKER_REGISTRY/esp32-toolchain
   variables:
     PLATFORM_NAME: "linux64"
-    ARCHIVE_TOOL: "tar czvf"
-    ARCHIVE_EXT: "tar.gz"
-  <<: *build_template_linux
 
 build_linux_x86:
-  tags:
-    - build
+  <<: *build_template_linux
   image: $CI_DOCKER_REGISTRY/esp32-toolchain-x86
   variables:
     PLATFORM_NAME: "linux32"
-    ARCHIVE_TOOL: "tar czvf"
-    ARCHIVE_EXT: "tar.gz"
-  <<: *build_template_linux
 
 build_macos:
+  <<: *build_template
   tags:
     - build_macos_case_sensitive
   variables:
     PLATFORM_NAME: "osx"
-    ARCHIVE_TOOL: "tar czvf"
-    ARCHIVE_EXT: "tar.gz"
-  <<: *build_template
   script:
     - *get_release_name
     - *build_ctng
@@ -120,26 +140,40 @@ build_macos:
     - *package_toolchain
 
 build_windows:
-  tags:
-    - build
+  <<: *build_template
   image: $CI_DOCKER_REGISTRY/esp32-toolchain-win-cross
   variables:
+    CONF_HOST: "i686-w64-mingw32"
     PLATFORM_NAME: "win32"
-    ARCHIVE_TOOL: "tar czvf"
-    ARCHIVE_EXT: "tar.gz"
-  <<: *build_template
   script:
     - *get_release_name
     - *build_ctng
     - *configure_common
     - *configure_docker
-    # Override options specific for Windows
-    - echo "CT_CANADIAN=y" >> .config
-    - echo "CT_HOST=\"i686-pc-mingw32\"" >> .config
-    - echo "CT_HOST_PREFIX=\"i686-w64-mingw32-\"" >> .config
-    - echo "CT_HOST_SUFFIX=\"\"" >> .config
-    - echo "# CT_GDB_CROSS_PYTHON is not set" >> .config
+    - *configure_crossbuild
     - *get_tarballs
     - *build_toolchain
     - *package_toolchain
 
+build_linux_armel:
+  <<: *build_template
+  image: $CI_DOCKER_REGISTRY/esp32-toolchain-arm-cross
+  variables:
+    CONF_HOST: "arm-linux-gnueabi"
+    PLATFORM_NAME: "linux-armel"
+  script:
+    - *get_release_name
+    - *build_ctng
+    - *configure_common
+    - *configure_docker
+    - *configure_linux_no_pie
+    - *configure_crossbuild
+
+    # To avoid the issue caused by running armel-binary on the armhf platform (RPi3):
+    # "liblto_plugin.so: cannot open shared object file: No such file or directory"
+    # This is a common case for dynamically linked binaries, not specfic liblto_plugin only
+    - echo "CT_STATIC_TOOLCHAIN=y" >> .config
+
+    - *get_tarballs
+    - *build_toolchain
+    - *package_toolchain
